# Generated by Django 2.2.2 on 2019-06-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wrestlers', '0007_delete_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('summary', models.CharField(blank=True, max_length=200, null=True)),
                ('outcome', models.CharField(blank=True, max_length=200, null=True)),
                ('losers', models.ManyToManyField(blank=True, related_name='losers', to='wrestlers.Wrestler')),
                ('winners', models.ManyToManyField(blank=True, related_name='winners', to='wrestlers.Wrestler')),
                ('wrestlers', models.ManyToManyField(to='wrestlers.Wrestler')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('location', models.CharField(default='Oakland Metro Oprah House', max_length=200)),
                ('matches', models.ManyToManyField(blank=True, related_name='matches', to='events.Match')),
            ],
        ),
    ]
