# Generated by Django 2.2.2 on 2019-06-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wrestler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('nickname', models.CharField(max_length=200)),
                ('affiliation', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=1000)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('D', 'Demon'), ('A', 'Angle'), ('U', 'Unsure'), ('Fl', 'Fluid'), ('AS', 'Asexual')], max_length=2)),
                ('birthdate', models.DateField(verbose_name='birthday')),
                ('weight', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('loses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('summary', models.CharField(max_length=200)),
                ('winners', models.CharField(max_length=200)),
                ('loosers', models.CharField(max_length=200)),
                ('wrestlers', models.ManyToManyField(to='wrestlers.Wrestler')),
            ],
        ),
    ]
