# Generated by Django 2.2.2 on 2019-06-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestlers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='loosers',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='winners',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='loses',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='wins',
            field=models.IntegerField(null=True),
        ),
    ]
