# Generated by Django 2.2.2 on 2019-06-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestlers', '0004_auto_20190620_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='outcome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
