# Generated by Django 2.2.2 on 2019-06-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestlers', '0005_match_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrestler',
            name='losses',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='wins',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
