# Generated by Django 2.2.2 on 2019-06-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestlers', '0002_auto_20190620_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wrestler',
            old_name='loses',
            new_name='losses',
        ),
        migrations.AlterField(
            model_name='match',
            name='loosers',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='match',
            name='winners',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='affiliation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='nickname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
