# Generated by Django 2.2.2 on 2019-06-30 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrestlers', '0006_auto_20190627_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
