# Generated by Django 2.2.2 on 2019-06-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='leauge',
            field=models.CharField(choices=[('HS', 'Hoodslam'), ('GLAM', 'Guilty Leathal Action Mayham'), ('SGTWS', 'Sexy Good Time Wresleing Show')], default='HS', max_length=5),
        ),
    ]
