# Generated by Django 2.2.2 on 2019-06-30 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_leauge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
    ]
